### ISSUE TITLE
Một số đóng góp cho anh em :D

### ISSUE THREAD

**Issue by thientu995** [phanxuanquang/Adobe-Camera-Profiles-Unlocker#2]
Nếu trường hợp anh em chỉ cần dùng [Camera Raw plug-in installer](https://helpx.adobe.com/camera-raw/kb/camera-raw-plug-in-installer.html)
Không dùng Photoshop hoặc Lightroom, thì mình vẫn chạy bình thường nhé, nên việc check cả 2 folder đều tồn tại thì hơi phí. Mình có sửa lại code như này:
![image](https://github.com/phanxuanquang/Adobe-Camera-Profiles-Unlocker/assets/15050790/8370e918-8f6c-44b1-8f30-c5c8c9516ddb)

Kết quả vẫn gen được file:
![image](https://github.com/phanxuanquang/Adobe-Camera-Profiles-Unlocker/assets/15050790/6c2e88ed-f40d-4c63-8c6f-b22a2c454c72)

Mình chỉ đóng góp thêm cho anh em để hoàn thiện thôi :D, mong chờ bản chạy 2 nền tảng win+mac
Thanks!

**Comment by phanxuanquang** [comment]
[Fixed in the v2.1](https://github.com/phanxuanquang/Adobe-Camera-Profiles-Unlocker/releases/tag/2.1)
