### ISSUE TITLE
Error: Cannot find Lightroom or Camera Raw on your device.

### ISSUE THREAD

**Issue by sitien173** [phanxuanquang/Adobe-Camera-Profiles-Unlocker#4]
![Screenshot 2024-08-06 100815](https://github.com/user-attachments/assets/b2f88328-6a00-4d81-a019-28d647599dbf)
![Screenshot 2024-08-06 101401](https://github.com/user-attachments/assets/852da789-5046-4e04-8a5c-56a5266bd957)

**Comment by phanxuanquang** [comment]
Make sure that the following directories exist:
- C:\ProgramData\Adobe\CameraRaw\CameraProfiles\Camera
- C:\ProgramData\Adobe\CameraRaw\Settings\Adobe\Profiles\Camera

Otherwise, try installing the latest version of Lightroom and Camera Raw

**Comment by sitien173** [comment]
The folder in path 'C:\ProgramData\Adobe\CameraRaw\CameraProfiles\Camera' is empty which was an error. Reinstall it again and It works. Thanks
