### ISSUE TITLE
Error: Cannot find  Camera Raw on your device.

### ISSUE THREAD

**Issue by tiamo405** [phanxuanquang/Adobe-Camera-Profiles-Unlocker#5]
C:\ProgramData\Adobe\CameraRaw của mình đầy đủ như câu trả lời trong 1 issues khác, mình đã cài lại camera raw nhưng vẫn k thấy ở laptop của mình

**Comment by phanxuanquang** [comment]
Bạn cài Camera Raw phiên bản mới nhất thử xem
